### ISSUE TITLE
no json files

### ISSUE THREAD

**Issue by choos11** [mks0601/ExAvatar_RELEASE#10]
What a nice job.But in the following code snippet from run_deca.py, I cannot find the output JSON files in flame_init/flame_params:

cmd = f'python demos/demo_reconstruct.py -i "{osp.join(root_path, "frames")}" --saveDepth True --saveObj True --rasterizer_type=pytorch3d --savefolder "{output_save_path}"'
os.system(cmd)

save_path = osp.join(root_path, 'flame_init', 'flame_params')
os.makedirs(save_path, exist_ok=True)
flame_shape_param = []
output_path_list = [x for x in glob(osp.join(output_save_path, '*.json'))]

**Comment by mks0601** [comment]
Hi, did you run `python copy_code.py` as in https://github.com/mks0601/ExAvatar_RELEASE/tree/main/fitting#custom-videos-your-own-videos? It copies some scripts of DECA in addition to `run_deca.py`.

**Comment by choos11** [comment]
> Hi, did you run `python copy_code.py` as in https://github.com/mks0601/ExAvatar_RELEASE/tree/main/fitting#custom-videos-your-own-videos? It copies some scripts of DECA in addition to `run_deca.py`.

Thank you, the issue has been resolved.

**Comment by HuynhNguyenPhuc** [comment]
> Hi, did you run `python copy_code.py` as in https://github.com/mks0601/ExAvatar_RELEASE/tree/main/fitting#custom-videos-your-own-videos? It copies some scripts of DECA in addition to `run_deca.py`.

I had run this script, but still cannot get the JSON file.

**Comment by mks0601** [comment]
could you just download [here](https://github.com/mks0601/PERSONA_RELEASE/releases/download/1.0/DECA.zip) and try again? It includes all necessary weights and code.

**Comment by HuynhNguyenPhuc** [comment]
> could you just download [here](https://github.com/mks0601/PERSONA_RELEASE/releases/download/1.0/DECA.zip) and try again? It includes all necessary weights and code.

Thanks for the quick response. I have solved my issue with this.
