### ISSUE TITLE
how long will fitting and avatar creation take on a 3090 24GB?

### ISSUE THREAD

**Issue by gt732** [mks0601/ExAvatar_RELEASE#11]
Thank you for releasing this paper/code! 

how long will fitting and avatar creation take on a 3090 24GB?

**Comment by mks0601** [comment]
depends on the duration of your phone scan. Assuming public datasets, such as NeuMan, it usually takes 2~3 hours. Once you create the avatar, animation/rendering can be done in real time.

**Comment by YaoBeiji** [comment]
Thank you for releasing this paper/code!

**Comment by gt732** [comment]
@mks0601 Gotcha thanks. I was able to get the code working on my machine and the fitting process did take a few hours. So if I understand the process correctly. 

If my goal is to animate my custom avatar using a ref video from the wild. The high level process is.

1. Use the fitting code on the video from the wild - extract SMPL-X data
2. Use the fitting code on my phone scan video - extract SMPL-X data
3. Use the SMPL-X data to train an avatar
4. Use the SMPL-X information from the video from the wild to animate my avatar

Does that sound correct?

Sorry if the questions are dumb I'm new to this field

Also is the only possible way to animate the avatar is through SMPL-X data? Is it possible to animate via dwpose information

https://github.com/IDEA-Research/DWPose

**Comment by mks0601** [comment]
Yeap you're correct. We fit SMPL-X to the pose detections from DWPose actually in the step 1 and 2 of yours.

**Comment by gt732** [comment]
@mks0601 Thanks!
