### ISSUE TITLE
docker image or dockerfile

### ISSUE THREAD

**Issue by XingFen-Xie** [mks0601/ExAvatar_RELEASE#16]
Hi, do you have a docker image or dockerfile for a customized dataset environment.It always reports some strange errors when running the code in question, probably due to the wrong version of some packages in the environment. Thank you!

**Comment by mks0601** [comment]
let me make it soon. fyi, as long as you install pytorch3d without problems, the code does not require specific versions of some packages.

**Comment by XingFen-Xie** [comment]
Thank you very much, I installed pytorch3d, but I still have some strange problems when running `python run.py`, and when I solve one I get another one. It seems that using `os.system(cmd)` causes some commands to be executed unsuccessfully without prompting, causing the next step to be entered without the result of the previous step, and then an error is reported.

**Comment by mks0601** [comment]
That's a good suggestion. I updated run.py as follow: https://github.com/mks0601/ExAvatar_RELEASE/blob/main/fitting/tools/run.py
Now, it will raise the error message and the script will be terminated once it meets an error.

**Comment by XingFen-Xie** [comment]
Thanks for the improvements. A docker environment would be nice, and if docker can be made it would be greatly appreciated! Looking forward to the docker release environment.Thanks again.

**Comment by mks0601** [comment]
https://github.com/mks0601/ExAvatar_RELEASE#install
