### ISSUE TITLE
Nonetype stats['mean_2d'] gradient error in train.py 

### ISSUE THREAD

**Issue by shamanneo** [mks0601/ExAvatar_RELEASE#2]
Hello,

Thank you very much for providing such an amazing open-source resource.

I am currently building a custom dataset that includes SMPL-X parameters and training an avatar using a train.py script. However, I encountered an issue during the training process.

On line 51 of train.py, the "grad" variable of stats["mean_2d"] is calculated as None, which causes the code to fail.

The exact error is as follows:

```
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main()
  File "train.py", line 51, in main
    stats['mean_2d_grad'] = torch.stack([x.grad.detach() for x in stats['mean_2d']])
  File "train.py", line 51, in <listcomp>
    stats['mean_2d_grad'] = torch.stack([x.grad.detach() for x in stats['mean_2d']])
AttributeError: 'NoneType' object has no attribute 'detach'
```

How can I resolve this issue?

Thank you.

**Comment by mks0601** [comment]
Are you able to run the code as it is without modifying it on existing datasets, such as NeuMan dataset?

**Comment by shamanneo** [comment]
Thank you for your prompt response.

As per your suggestion, I will review the NeuMan dataset.

May I kindly ask if the "test_split.txt" and "train_split.txt" files for the NeuMan dataset should also follow the naming format of 00000, 00001, and so forth?

It appears that the preprocessed NeuMan dataset provided does not include specific information regarding the required format.

**Comment by mks0601** [comment]
They are from NeuMan dataset's official release, not made by me.

**Comment by shamanneo** [comment]
I confirmed that, as you suggested, the same "nonetype grad" issue occurs with the Neuman dataset as well.

**Comment by mks0601** [comment]
![image](https://github.com/user-attachments/assets/196d17c5-ba68-4159-a3a2-0da041785e05)

This is what I can see from the current repo. I can't see any problems. What I did is 1) clone the repo, 2) make common/utils/human_model_files, 3) make data/NeuMan/data, and 4) run `python train.py --subject_id citron`.

**Comment by Connaught0** [comment]
> Thank you for your prompt response.
> 
> As per your suggestion, I will review the NeuMan dataset.
> 
> May I kindly ask if the "test_split.txt" and "train_split.txt" files for the NeuMan dataset should also follow the naming format of 00000, 00001, and so forth?
> 
> It appears that the preprocessed NeuMan dataset provided does not include specific information regarding the required format.

I found that code to create such split file  from the code in data_io/Neuman_helper
[https://github.com/apple/ml-neuman/blob/0149d258b2afe6ef65c91557bba9f874675871e4/data_io/neuman_helper.py#L149](url)

**Comment by mks0601** [comment]
Yeap I made the split files using that code. Let me share the split files in here. This is also added to README as well.
https://drive.google.com/drive/folders/1L5KC4QIRX_ljQ_vyrIXV11FgynnuCDb8?usp=sharing

**Comment by shamanneo** [comment]
Hello,

Are you using multiple GPUs when running the train.py script?

We are working in a multi-GPU environment, and when we use CUDA_VISIBLE_DEVICES=N, the error doesn't occur. However, when we don't use it, we encounter an error where "grad" is None.

**Comment by mks0601** [comment]
Hi, my server has multiple GPUs, but I only use a single GPU to train/test ExAvatar.
Before training/testing, I execute 'export CUDA_VISIBLE_DEVICES=N' as you said, where N is the GPU ID that I'd like to use.
Without executing that cmd, the system will use multiple GPUs in default, which could make some problems when gathering computation graphs.

**Comment by shamanneo** [comment]
We have also confirmed this fact.

Once again, thank you for your amazing work, and we appreciate your help.
