### ISSUE TITLE
How to get file FLAME_FEMALE.pkl, FLAME_MALE.pkl and FLAME_NEUTRAL.pkl?

### ISSUE THREAD

**Issue by justinvo277** [mks0601/ExAvatar_RELEASE#20]
I followed the instructions to download the file in the README, but when I downloaded and extracted it, I didn't find any files with that name. There are 3 files with different names?

**Comment by mks0601** [comment]
you need to download flame 2020

**Comment by justinvo277** [comment]
![image](https://github.com/user-attachments/assets/a409ca6e-f52e-4b57-9b21-061d6627b06c)
I downloaded this. Is this exactly what you instructed?

**Comment by mks0601** [comment]
yes

**Comment by justinvo277** [comment]
![image](https://github.com/user-attachments/assets/a9e888ec-42c9-430c-ae20-55e49b3e5229)

I unzipped the files with different names in the README and my job is to just rename those files to be the same as in the README?

**Comment by mks0601** [comment]
yes

**Comment by justinvo277** [comment]
Thanks for your support !!!
