### ISSUE TITLE
No such file cameras.npz

### ISSUE THREAD

**Issue by justinvo277** [mks0601/ExAvatar_RELEASE#21]
![image](https://github.com/user-attachments/assets/0c735b35-5178-43f5-a45e-590f5d648286)
When I run it with a Xhuman dataset that you have preprocessed, I get an error like the one in the picture, there is no file like v in the Xhuman folder.

**Comment by mks0601** [comment]
did you download X-Humans dataset?

**Comment by justinvo277** [comment]
![image](https://github.com/user-attachments/assets/e294cf38-9b93-4621-924a-4fd55b52115b)
I just downloaded this

**Comment by mks0601** [comment]
You need to first download original X-Humans dataset and then paste our pre-processed files to the original dataset

**Comment by justinvo277** [comment]
![image](https://github.com/user-attachments/assets/368e9966-e7ba-4345-8462-c2363c7e9cc0)
I sent a request to download X-human but it took about 2 weeks for me to receive a response. I try running a custom dataset and the following issues:

**Comment by mks0601** [comment]
please read the instruction carefully before making an issue. you need to run hand4whole to get smplx_init.

**Comment by justinvo277** [comment]
Thanks for your support !!!
