### ISSUE TITLE
How can I obtain and organize the correct directory in fitting?

### ISSUE THREAD

**Issue by nothonfz** [mks0601/ExAvatar_RELEASE#23]
I downloaded smplx-1.1 and flame2020, and placed all the downloaded files into fitting/common/utils. However, I couldn't find MANO_SMPLX_vertex_ids.pkl, SMPL-X__FLAME_vertex_ids.npy, and smplx_flip_correspondences.npz in the smplx folder. The number of files in the flame folder also doesn’t match.
<img width="596" alt="3e839693466e805efd148d64176f3cc" src="https://github.com/user-attachments/assets/d519bd61-e9a7-4e62-92f0-6417b4e76575">
Did I miss downloading some files?

**Comment by nothonfz** [comment]
Thank you for your quick response. I've completed the missing files in the smplx folder and downloaded the relevant compressed files from the FLAME website. I guess I should rename female_model.pkl from flame2020 to FLAME_FEMALE.pkl, male_model.pkl to FLAME_MALE.pkl, and generic_model.pkl to FLAME_NEUTRAL.pkl. Is that correct? Also, I couldn't find the files flame_static_embedding.pkl and flame_dynamic_embedding.npy.<img width="584" alt="a73782a753a3aef397e85d7bf72edd6" src="https://github.com/user-attachments/assets/dfb0ebdc-e370-403c-8a16-1fd410d2c2c0">

**Comment by mks0601** [comment]
For the FLAME files, yes you're correct.
For others, see https://github.com/mks0601/ExAvatar_RELEASE/issues/3

**Comment by nothonfz** [comment]
Thanks！
