### ISSUE TITLE
Neuman dataset

### ISSUE THREAD

**Issue by serizawa-04013958** [mks0601/ExAvatar_RELEASE#26]
Thank you for your code!!
I tried your code on neuman dataset. but result was bad,
It seems preprocess work well, can you help us for debugging?
I shared preprocessed dataset here

https://drive.google.com/file/d/1ZQ8Wwz_3DmCte07zpoQKHxFot5zEAXuJ/view?usp=drive_link

![0](https://github.com/user-attachments/assets/4109a4d9-cca6-4a6a-bab8-8391a5aa0b87)

**Comment by mks0601** [comment]
did you change some training code?

**Comment by serizawa-04013958** [comment]
No I didn't.
I used released colmap data from neuman, and work preprocess code.
then tried training code in Custom mode.

**Comment by serizawa-04013958** [comment]
since smplx_params_smoothed did not work, we used smpl_optimized/smplx_params

**Comment by mks0601** [comment]
The original code does not use smplx_params_smoothed for NeuMan dataset, while uses it for Custom dataset. Why did you try smoothed one? Did you run train with setting dataset='NeuMan' in here(https://github.com/mks0601/ExAvatar_RELEASE/blob/69e12bb1bee4d0401b304c3ab245a6c8658a8bc2/avatar/main/config.py#L40)?

**Comment by serizawa-04013958** [comment]
Yes, I did.
I run training with setting dataset='NeuMan'

**Comment by mks0601** [comment]
I haven't seen these kinds of failure cases... could you share your rendered images on NeuMan dataset?

**Comment by serizawa-04013958** [comment]
Do you mean the rendering result?
here is the result of main/test.py

https://drive.google.com/file/d/1-DfQ-hG6MLiQU97YXAbJgv03L37BPVA7/view?usp=drive_link

**Comment by mks0601** [comment]
It seems you're loading some wrong data from the dataloader like wrong camera parameters or wrong smplx parameters. could you check again? please try with newly cloned without any modification.

**Comment by serizawa-04013958** [comment]
I recreated dataset, and it was because of data index problem.
after recreation, training worked well! thank you.

**Comment by nadhiranoor** [comment]
@serizawa-04013958 would you please share the recreated dataset for neuman training? thank you!
