### ISSUE TITLE
animate avatar using simple SMPL pose parameters

### ISSUE THREAD

**Issue by gt732** [mks0601/ExAvatar_RELEASE#27]
Hi,

Thanks for the hard work here! I was able to get good results following the instructions. Here is my personal avatar!

https://github.com/user-attachments/assets/855b48f0-89ab-43e8-b8cb-78d1e6271d5a

My question is how can I animate my avatar by using simple SMPL pose/camera parameters, I tried following the fitting code to get an understanding but it looks like the model uses a special format that comes from the SMPL optimized after the fitting run. 

I would use fitting on a video from the wild but it can take hours just a small clip.

Can we use SMPL parameters from projects like:

https://github.com/brjathu/PHALP

https://github.com/mkocabas/VIBE

https://github.com/mkocabas/PARE

Also the paper mentions real time inferencing is possible with the avatar, any resources or code snippets you can point me to?

Thanks!!

**Comment by mks0601** [comment]
ExAvatar requires SMPL-X, not SMPL parameters. SMPL parameters do not have hand/face information, and body kinematic chain is slightly different from SMPL-X.

**Comment by gt732** [comment]
@mks0601 makes sense, thanks! I'll look into getting the SMPL-X parameters and trying that.
