### ISSUE TITLE
How to get flame files flame_dynamic_embedding.npy and flame_static_embedding.pkl ?

### ISSUE THREAD

**Issue by R132** [mks0601/ExAvatar_RELEASE#3]
Thanks for sharing your nice work! 
Couldn`t find flame_dynamic_embedding.npy and flame_static_embedding.pkl, where can I get them?

**Comment by R132** [comment]
Found them here: https://github.com/soubhiksanyal/RingNet/tree/master/flame_model
Are they the right version?

**Comment by mks0601** [comment]
Hi, yes that is the right one.

**Comment by R132** [comment]
> Hi, yes that is the right one.

THX
