### ISSUE TITLE
"TypeError: Caught TypeError in replica 0 on device 0" during fit.py execution

### ISSUE THREAD

**Issue by NgdHung31** [mks0601/ExAvatar_RELEASE#31]
Hi Gyeongsik,

First off, I’d like to thank you for this incredible project! The approach and potential here are impressive, and I’m really excited to dive deeper into it.

I ran into an issue while executing python fit.py --subject_id gyeongsik. Specifically, I’m seeing the following error:

`TypeError: Caught TypeError in replica 0 on device 0.`

It happens when the script runs into this line https://github.com/mks0601/ExAvatar_RELEASE/blob/69e12bb1bee4d0401b304c3ab245a6c8658a8bc2/fitting/main/fit.py#L117
Could I ask which Python and PyTorch versions you’re using for this project? I’d like to ensure I’m aligned with your environment to troubleshoot effectively.

Thank you again for sharing this work with the community. Looking forward to any guidance you can provide.

Best regards

**Comment by mks0601** [comment]
Hi, I used 2.4.1+cu121, but I don't think your problem is about pytorch version. Did you run `export CUDA_VISIBLE_DEVICES=0` before running the fitting? If not, could you do that?

**Comment by NgdHung31** [comment]
Hi,
Thank you so much for the suggestion! I assume fitting.py is using gpu index from run.py file, I tried running export CUDA_VISIBLE_DEVICES=0 as you recommended, and that indeed resolved the previous error—really appreciate your help with that.

btw, I’ve run into a new issue:
`TypeError: lbs() missing 2 required positional arguments: 'parents' and 'lbs_weights'`
It seems to be related to missing arguments in the lbs() function. it is missing 2 args added by you in the definition of the lbs function.
where the terminal stops: 
https://github.com/mks0601/ExAvatar_RELEASE/blob/69e12bb1bee4d0401b304c3ab245a6c8658a8bc2/fitting/common/utils/smplx/smplx/body_models.py#L2104-L2108
and this is where the lbs function is defined:
https://github.com/mks0601/ExAvatar_RELEASE/blob/69e12bb1bee4d0401b304c3ab245a6c8658a8bc2/fitting/common/utils/smplx/smplx/lbs.py#L156-L167

Do you have any insights on what might be causing this? I’d be grateful for any guidance you can provide.

Thanks again for your assistance!

Best,

**Comment by mks0601** [comment]
Hi, could you let me know the full error message? I do not have any errors on my side

**Comment by NgdHung31** [comment]
Of course, here is the screenshot where the error starts, I noticed the lbs function in the definition requires 11 arguments, but in the code that calls the lbs function it is only given 9 arguments.
![Screenshot from 2024-10-30 00-33-09](https://github.com/user-attachments/assets/728c6544-bdee-408f-8ba2-1840d190706d)

**Comment by mks0601** [comment]
please check this line.
https://github.com/mks0601/ExAvatar_RELEASE/blob/69e12bb1bee4d0401b304c3ab245a6c8658a8bc2/fitting/common/utils/flame.py#L5
My one does not use utils/smplx, but use the standard smplx

**Comment by NgdHung31** [comment]
Oh, I see! I initially thought the `smplx` library you included in the `utils` folder would be sufficient. But after installing `smplx` via `pip`, everything is working perfectly now. Thank you so much for your helpful guidance!

I’m sorry for the delayed response last night; it was quite late here. Once again, I really appreciate your patience and support.

Best regards

**Comment by mks0601** [comment]
`pip install smplx`

**Comment by azureovo** [comment]
> `pip install smplx`
Thanks for your reply! I solved this problem.
You're really good and patient, I really appreciate your support.
