### ISSUE TITLE
Process NeuMan by `Custom videos (your own videos)`

### ISSUE THREAD

**Issue by sylcito** [mks0601/ExAvatar_RELEASE#32]
Hello, great job! 
I followed the process in the "fitting/tools/custom videos" section to process the NeuMan dataset and compared the results with the items in the preprocessed link you provided. I found that in the colmap step, the `sparse/cameras.txt` generated by your run_colmap.py script has the following content:
```txt
# Camera list with one line of data per camera:
# CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 1
1 PINHOLE 1259 708 1096.6 1096.6 629.5 354
``` 
while mine looks like this:
```txt
# Camera list with one line of data per camera:
# CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 3
24 SIMPLE_RADIAL 1259 708 4723.8757606179779 629.5 354 1.071542743605485
16 SIMPLE_RADIAL 1259 708 4945.1540410829966 629.5 354 0.091680160692852453
15 SIMPLE_RADIAL 1259 708 4850.5004111446306 629.5 354 0.11887170842931057
``` 

As a result, my sparse/points3D.txt only contains 54 lines, whereas yours has 19,498 lines. Do you have any suggestions for this situation? I adjusted the run_colmap.py script in the colmap feature_extractor section by adding --ImageReader.single_camera 1 --ImageReader.camera_model PINHOLE, and then its content changed to:
```txt
# Camera list with one line of data per camera:
# CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 1
1 PINHOLE 1259 708 23074.50297464255 19602.994403607907 629.5 354
```
Note that the focal_x and focal_y is wired. 

Any advices? 

Best wishes!

**Comment by mks0601** [comment]
Hi, thanks for your comment. I actually missed to add `--ImageReader.single_camera 1 --ImageReader.camera_model PINHOLE`, so I've just added it. Using it, I can get almost the same cameras.txt and points3D.txt from citron sequence. Which sequence are you trying?

**Comment by sylcito** [comment]
Hi, thanks for your response. I previously tested with `seattle`, and now I have re-checked your updated script with `citron`. The output of sparse/cameras.txt is as follows:
```txt
# Camera list with one line of data per camera:
# CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]
# Number of cameras: 1
1 PINHOLE 1276 717 1271.4045672414638 575.71005547377638 638 358.5
``` 
1. The focal_x and focal_y (1271.4045672414638 575.71005547377638) are still different from yours 1096.6 1096.6. 

2. The number of lines in points3D.txt is still very few. What do you think?

P.S. My approach is to use the original data from NeuMan`https://docs-assets.developer.apple.com/ml-research/datasets/neuman/dataset.zip`, extract Citron, move the images folder separately, create frame_list_all.txt (00000-00036), and then run run_colmap.py. Finally, compare those files with yours (https://drive.google.com/drive/folders/15-V9EG21hT4pVhuBdHY3-lpvKjCuHbEU?usp=sharing) Is there any issue with this process?

**Comment by mks0601** [comment]
I'm not sure what makes difference, but this is my result

```
1 PINHOLE 1276 717 1004.8082387723571 999.35689617706032 638 358.5
```

and I have 17901 lines in `points3D.txt`, which seems good.  I just ran [this](https://github.com/mks0601/ExAvatar_RELEASE/blob/main/fitting/tools/code_to_copy/run_colmap.py) with the same images as yours.

**Comment by mks0601** [comment]
could you check if there is something wrong in your pipeline?

**Comment by sylcito** [comment]
@mks0601 Hi, I’m still troubleshooting the issue with COLMAP, but I directly reused your processed `sparse` folder to continue with the workflow. When I reached step:
https://github.com/mks0601/ExAvatar_RELEASE/blob/fc92362b6406b3c81ac4273f72ca2befc94c7e80/fitting/tools/smooth_smplx_params.py#L191 
I noticed that the `cam_params` folder was missing. Even when enabling `--use_colmap` in the previous steps, this folder was not generated. After reviewing `NeuMan.py`, I manually created `cam_params` following the format of:
https://github.com/mks0601/ExAvatar_RELEASE/blob/fc92362b6406b3c81ac4273f72ca2befc94c7e80/fitting/data/NeuMan/NeuMan.py#L45
However, the exported smooth file shows a significant misalignment between SMPLX and the images. Is there a more systematic approach to address this? Ideally, running `run.py` should automatically generate a properly configured `cam_params` folder.

**Comment by mks0601** [comment]
As in [here](https://github.com/mks0601/ExAvatar_RELEASE/tree/main/fitting#custom-videos-your-own-videos), when camera is moving like NeuMan dataset, you should not use the virtual camera parameters as they have identity camera extrinsics. Instead, you need to use colmap to obtain camera parameters. Also, NeuMan dataset is downsampled to 5 fps, which means smoothing smplx parameter does not make sense. 5 fps is too sparse. That is the reason why I use 'smplx_optimized' instead of 'smplx_optimized_smoothed' in NeuMan dataset.
