### ISSUE TITLE
FLAME file not found

### ISSUE THREAD

**Issue by upauparuru** [mks0601/ExAvatar_RELEASE#33]
Thanks for the great job 
I would like to download the following file, but I can't find it.
```
flame/flame_dynamic_embedding.npy
flame/FLAME_FEMALE.pkl
flame/flame_static_embedding.pkl
```
etc. but I can't find the files. download https://flame.is.tue.mpg.de/download.phpから “FLAME 2020 (fixed mouth, improved expressions, more data) I could not find the file. Please let me know which file to download. Or if you have changed the name of the downloaded file, please let me know which file you have changed the name of.

**Comment by mks0601** [comment]
You can google those file name. I remember I downloaded them from https://github.com/soubhiksanyal/RingNet/blob/master/dynamic_contour_embedding.py

**Comment by upauparuru** [comment]
@mks0601 
Thank you.
I found https://github.com/soubhiksanyal/RingNet/tree/master/flame_model
