### ISSUE TITLE
Chin does not fit well with SMPL

### ISSUE THREAD

**Issue by upauparuru** [mks0601/ExAvatar_RELEASE#35]
Excellent, thank you.
I don't think this question is a scripting problem, but if you know the cause, I would like to know.
According to the attached image, the chin is deformed when aligning the SMPL. Do you know why this is?
Is the SMPL file corrupted?

![0_smplx](https://github.com/user-attachments/assets/72a06c39-d0f8-462d-bdb8-ea4f0eb28872)

**Comment by mks0601** [comment]
Did you install DECA properly?

https://github.com/mks0601/ExAvatar_RELEASE/issues/13

**Comment by upauparuru** [comment]
Sorry, I didn't check!
Thank you!
