### ISSUE TITLE
How can I obtain the correct cam_param for the Neuman dataset?

### ISSUE THREAD

**Issue by xiezhy6** [mks0601/ExAvatar_RELEASE#4]
Hi, thanks for sharing your excellent work!

When I  try to render the mesh of smplx for Neuman dataset, I found the pre-processed data you provided (in this [link](https://drive.google.com/drive/folders/15-V9EG21hT4pVhuBdHY3-lpvKjCuHbEU) ) does not contain the cam_param.

So I try to use the virtual camera generation script (in this [script](https://github.com/mks0601/ExAvatar_RELEASE/blob/main/fitting/tools/make_virtual_cam_params.py)) to generate the camera parameter for rendering. However, the rendering results is incorrect as shown bellow.

![0_smplx](https://github.com/user-attachments/assets/f794e6a1-1ec2-4bbf-a8eb-783992d83886)

By the way, I have also try to render the mesh for the gyeongsik dataset provided in this [link](https://drive.google.com/file/d/1YGJZWWpw_R63HiZu65smV6Lrksqa6EOu/view), which uses the virtual camera parameter generated by the above [script](https://github.com/mks0601/ExAvatar_RELEASE/blob/main/fitting/tools/make_virtual_cam_params.py). The rendered result is correct as shown bellow.

![110_smplx](https://github.com/user-attachments/assets/920324d4-fd73-4336-bca3-bee3c5023065)

I seems that to render smplx mesh, the camera parameters for different dataset (NeuMan dataset and gyeongsik) are generated in different manner. Would you please tell me how to obtain the 'correct' camera parameters for NeuMan dataset?

Thanks a lot!

**Comment by mks0601** [comment]
Hi,

Each dataset could have different camera parameter.
For the NeuMan dataset, you can check it from the dataloader like [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/5ef87f4db2a91630cf8061ff43e63c7fc934b4a6/fitting/data/NeuMan/NeuMan.py#L35) and [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/5ef87f4db2a91630cf8061ff43e63c7fc934b4a6/avatar/data/NeuMan/NeuMan.py#L34).

**Comment by xiezhy6** [comment]
> Hi,
> 
> Each dataset could have different camera parameter. For the NeuMan dataset, you can check it from the dataloader like [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/5ef87f4db2a91630cf8061ff43e63c7fc934b4a6/fitting/data/NeuMan/NeuMan.py#L35) and [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/5ef87f4db2a91630cf8061ff43e63c7fc934b4a6/avatar/data/NeuMan/NeuMan.py#L34).

After using the correct camera parameter, the rendered smplx seems normal.

However, the rendered result (from this [script](https://github.com/mks0601/ExAvatar_RELEASE/blob/main/fitting/tools/smooth_smplx_params.py)) still fails to meet the performance you provide under the folder 'renders'. The comparison of the rendered results are shown bellow, (upper: you provide in the pre-process data, lower: the rendered results generated by [script](https://github.com/mks0601/ExAvatar_RELEASE/blob/main/fitting/tools/smooth_smplx_params.py) )

Would you please tell what opration I am missing to obtain the well-aligned rendered results like you provided?

Thanks a lot.

![00032_smplx](https://github.com/user-attachments/assets/cdae25f7-d106-4237-81e6-3ac490bbb46b)
![32_smplx](https://github.com/user-attachments/assets/7149d324-0d4d-4ba1-85a5-7194998e0855)

**Comment by mks0601** [comment]
Hi, the smoothing code assumes input SMPL-X parameters are from reasonable frame rates of a video. For example, 30 fps. However, NeuMan dataset is released after being downsampled to 5 fps, so it would be hard to apply any smoothing code. 5 fps is too sparse to apply some temporal smoothing stuff.

**Comment by xiezhy6** [comment]
Get it! Without conducting the smoothing operation, the rendered results get correct. Thanks a lot!

**Comment by MoyGcc** [comment]
Hi Gyeongsik @mks0601, a very quick question: have you re-run COLMAP on NeuMan dataset or just taken what the original dataset provides? Somehow I cannot render the SMPL-X to match the images using the cameras provided by NeuMan. Thanks!

**Comment by mks0601** [comment]
I used the original camera parameters without re-running COLMAP. How do you load camera parameters?

**Comment by MoyGcc** [comment]
> I used the original camera parameters without re-running COLMAP. How do you load camera parameters?

Thanks for the prompt response! It's very good to know! I used the same way as you pointed out: https://github.com/mks0601/ExAvatar_RELEASE/blob/5ef87f4db2a91630cf8061ff43e63c7fc934b4a6/avatar/data/NeuMan/NeuMan.py#L34
I initially saw the mismatch and thought the COLMAP has been rerun. I will double check my visualization code.

**Comment by mks0601** [comment]
sure. you can post minimally implemented your rendering code here if you want.

**Comment by MoyGcc** [comment]
> sure. you can post minimally implemented your rendering code here if you want.

Thanks for offering that! I just compared with your visualization code and it seems like all optimized SMPL-X parameters are in the camera space (rendering with identity matrix for Rt). I used the loaded Rt from COLMAP to render based on the optimized SMPLX- parameters and that's why there is a mismatch. Now I used an identity matrix for Rt and now it matches. Could you please correct me if I don't understand correctly?

**Comment by mks0601** [comment]
You're correct. All optimized smplx parameters are in camera coordinate space. That's the reason why I convert the coordinates to the world coordinates when creating the avatar in [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/f506f6a3b1e9299682afab184ba72a04061fef8c/avatar/main/model.py#L56).
