### ISSUE TITLE
The facial UV map seems bad

### ISSUE THREAD

**Issue by hengyu-wang** [mks0601/ExAvatar_RELEASE#41]
Hello, congratulations on your work being accepted by ECCV. I encountered a problem in processing the dataset. When I used DECA to process the people_snap_shot dataset, I found that the facial UV map I got was as follows. The forehead was black. Can you tell me the reason?
![image](https://github.com/user-attachments/assets/d4312efd-55f9-4bc6-8a48-9558e6f92d93)
Rendering results for some frames look bad：
![image](https://github.com/user-attachments/assets/3e7639a3-f578-4707-9b20-64ad8191a24f)
I would be very grateful to hear from you！

**Comment by mks0601** [comment]
Hi, did you follow the fitting process from scratch? I found that some people run DECA without proper model files. I added a line to check this like [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/90335954adbbcfc3f149e477ca8586dcc28fd3d9/fitting/tools/code_to_copy/run_deca.py#L22). Could you first check whether you ran DECA properly? You can also check `data/Custom/data/$SUBJECT_ID/flame_init/renders`. 

Another thing you can see is `data/Custom/data/$SUBJECT_ID/smplx_optimized/face_texture_mask.png`. Could you show this as well? BTW, I'm not sure why you have gray background at `face_texture.png', but it should have black background as attached UVmap.
![face_texture](https://github.com/user-attachments/assets/5c613221-d552-4fab-96dc-57e52fa5c5b7)

**Comment by xiaoduoo** [comment]
Hello, I have reviewed the previous issues and solutions. The problem I am facing is that during the fitting process, the chin is normal in my smplx_optimized.mp4, but there is an issue with the chin in smplx_optimized_smoothed.mp4. What could be the possible cause of this?

**Comment by hengyu-wang** [comment]
> Hi, did you follow the fitting process from scratch? I found that some people run DECA without proper model files. I added a line to check this like [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/15640a2047453a4d237601a00ab77597be077d25/fitting/tools/code_to_copy/run_deca.py#L22). Could you first check whether you ran DECA properly? You can also check `data/Custom/data/$SUBJECT_ID/flame_init/renders`.
> 
> Another thing you can see is `data/Custom/data/$SUBJECT_ID/smplx_optimized/face_texture_mask.png`. Could you show this as well? BTW, I'm not sure why you have gray background at `face_texture.png', but it should have black background as attached UVmap. ![face_texture](https://private-user-images.githubusercontent.com/13601723/396676581-5c613221-d552-4fab-96dc-57e52fa5c5b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTgyMjIsIm5iZiI6MTczNDUxNzkyMiwicGF0aCI6Ii8xMzYwMTcyMy8zOTY2NzY1ODEtNWM2MTMyMjEtZDU1Mi00ZmFiLTk2ZGMtNTdlNTJmYTVjNWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDEwMzIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjg2Yzg1ODc5ZDgwZmNlZmExOTVmZmNiNTg5N2M2NzhmMzhmZWM4ZWY2YmExOWNjYTVlZjU1YWEwODBkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zGdNjPUKC-SFkqdqNf101veSYp717MFM--h77KFjKnQ)

What I showed above is the result in flame_parmas_out, I checked smplx_optimized/face_texture.png and smplx_optimized/face_texture-mask.png. It seems to be normal：
![image](https://github.com/user-attachments/assets/f5ee52d7-de32-4d38-b862-78fa487d8787)
![image](https://github.com/user-attachments/assets/dfe4fbda-e2b2-4e8e-90a5-d67ba941b209)

**Comment by xiaoduoo** [comment]
> > 您好，我查看了之前的问题和解决方案。我面临的问题是，在拟合过程中，我的 smplx_optimized.mp4 中的下巴是正常的，但 smplx_optimized_smoothed.mp4 中的下巴有问题。这可能是什么原因造成的？
> 
> 你视频的 fps 是多少？请分享你的原创视频

My FPS is 7.Can this link (https://github.com/xiaoduoo/data) allow others to see my videos? I am a beginner, and I really appreciate your patience and help. Thank you so much!

**Comment by hengyu-wang** [comment]
> > > Hi, did you follow the fitting process from scratch? I found that some people run DECA without proper model files. I added a line to check this like [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/15640a2047453a4d237601a00ab77597be077d25/fitting/tools/code_to_copy/run_deca.py#L22). Could you first check whether you ran DECA properly? You can also check `data/Custom/data/$SUBJECT_ID/flame_init/renders`.
> > > Another thing you can see is `data/Custom/data/$SUBJECT_ID/smplx_optimized/face_texture_mask.png`. Could you show this as well? BTW, I'm not sure why you have gray background at `face_texture.png', but it should have black background as attached UVmap. ![face_texture](https://private-user-images.githubusercontent.com/13601723/396676581-5c613221-d552-4fab-96dc-57e52fa5c5b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTgyMjIsIm5iZiI6MTczNDUxNzkyMiwicGF0aCI6Ii8xMzYwMTcyMy8zOTY2NzY1ODEtNWM2MTMyMjEtZDU1Mi00ZmFiLTk2ZGMtNTdlNTJmYTVjNWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDEwMzIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjg2Yzg1ODc5ZDgwZmNlZmExOTVmZmNiNTg5N2M2NzhmMzhmZWM4ZWY2YmExOWNjYTVlZjU1YWEwODBkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zGdNjPUKC-SFkqdqNf101veSYp717MFM--h77KFjKnQ)
> > 
> > 
> > What I showed above is the result in flame_parmas_out, I checked smplx_optimized/face_texture.png and smplx_optimized/face_texture-mask.png. It seems to be normal： ![image](https://private-user-images.githubusercontent.com/120445772/396895526-f5ee52d7-de32-4d38-b862-78fa487d8787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDkyMjMsIm5iZiI6MTczNDU0ODkyMywicGF0aCI6Ii8xMjA0NDU3NzIvMzk2ODk1NTI2LWY1ZWU1MmQ3LWRlMzItNGQzOC1iODYyLTc4ZmE0ODdkODc4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxOTA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDkyNmQxNGJmYmRlMDkwNmRlNzY4OTI1YTkzYzc2NTNmMmViMmQzZjZkZTM0MjU5NTFlZDI2Yjk3NzU4YzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8ubfR2d9_aVINXbg5t1JhtvNVkZhJj6tYajOaIe22r8) ![image](https://private-user-images.githubusercontent.com/120445772/396896555-dfe4fbda-e2b2-4e8e-90a5-d67ba941b209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDkyMjMsIm5iZiI6MTczNDU0ODkyMywicGF0aCI6Ii8xMjA0NDU3NzIvMzk2ODk2NTU1LWRmZTRmYmRhLWUyYjItNGU4ZS05MGE1LWQ2N2JhOTQxYjIwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxOTA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTc2YjkxMjk0MDg0ZmFiNDUwYzkzZDBkZDI1Nzk0MGNiMDU5NmM3NjczOTMwMjc5MzczYmM4ZDg2MWU5ZmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tEbiI8MBWUoCsPVAb7g9sCcL-7lwfK7hgqBo6q9Hv_k)
> 
> You can ignore flame_params_out. They are not used when making avatars.

Thanks for your help!

**Comment by mks0601** [comment]
> > > 您好，我查看了之前的问题和解决方案。我面临的问题是，在拟合过程中，我的 smplx_optimized.mp4 中的下巴是正常的，但 smplx_optimized_smoothed.mp4 中的下巴有问题。这可能是什么原因造成的？
> > 
> > 
> > 你视频的 fps 是多少？请分享你的原创视频
> 
> My FPS is 31.5.Can this link (https://github.com/xiaoduoo/data) allow others to see my videos? I am a beginner, and I really appreciate your patience and help. Thank you so much!

You can post your original video, smplx_optimized.mp4, and smplx_optimized_smoothed.mp4 with Google drive.

**Comment by xiaoduoo** [comment]
> > > > 您好，我查看了之前的问题和解决方案。我面临的问题是，在拟合过程中，我的 smplx_optimized.mp4 中的下巴是正常的，但 smplx_optimized_smoothed.mp4 中的下巴有问题。这可能是什么原因造成的？
> > > 
> > > 
> > > 你视频的 fps 是多少？请分享你的原创视频
> > 
> > 
> > My FPS is 31.5.Can this link (https://github.com/xiaoduoo/data) allow others to see my videos? I am a beginner, and I really appreciate your patience and help. Thank you so much!
> 
> You can post your original video, smplx_optimized.mp4, and smplx_optimized_smoothed.mp4 with Google drive.

Thank you for your guidance. Here is the link to my video: https://drive.google.com/drive/folders/1H9qKa_XvJP3h4s_SyDDGlcuiprf7VhQK?usp=drive_link.

**Comment by xiaoduoo** [comment]
@mks0601 I found that the images in fitting/output/result/00028/smplx_optimized/renders are obviously incorrect, so the generated renders_smoothed are also problematic. However, the files under fitting/output/result/00028/smplx_optimized are normal. What could be the reason for this?

**Comment by hengyu-wang** [comment]
> Hi, did you follow the fitting process from scratch? I found that some people run DECA without proper model files. I added a line to check this like [here](https://github.com/mks0601/ExAvatar_RELEASE/blob/15640a2047453a4d237601a00ab77597be077d25/fitting/tools/code_to_copy/run_deca.py#L22). Could you first check whether you ran DECA properly? You can also check `data/Custom/data/$SUBJECT_ID/flame_init/renders`.
> 
> Another thing you can see is `data/Custom/data/$SUBJECT_ID/smplx_optimized/face_texture_mask.png`. Could you show this as well? BTW, I'm not sure why you have gray background at `face_texture.png', but it should have black background as attached UVmap. ![face_texture](https://private-user-images.githubusercontent.com/13601723/396676581-5c613221-d552-4fab-96dc-57e52fa5c5b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTYwMjksIm5iZiI6MTczNDYxNTcyOSwicGF0aCI6Ii8xMzYwMTcyMy8zOTY2NzY1ODEtNWM2MTMyMjEtZDU1Mi00ZmFiLTk2ZGMtNTdlNTJmYTVjNWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEzNDIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MmY0MzE3ZWVlM2QzNTVhNzg1ZTc4YTNhZmQxYjEzMDIwM2I4OThlY2YyMzE5Mzg1NjZkMzY3NTVhMzY2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pFxomY9VUYNmn_y0WauyHf8aXxNpUbkQ8Tqn92Kpdpo)

Hi, when I run segment-anything I find that some images don't look right, has this happened to you? Also if I want to train avatars on monocular camera data, do I need to run colmap? Thank you very much for your answer！
![image](https://github.com/user-attachments/assets/17768554-a8a8-458a-8ecf-292aa6bda3b9)
![image](https://github.com/user-attachments/assets/fbf552b2-ac8a-4d93-a752-7c25c3351b01)

**Comment by mks0601** [comment]
Such errors are okay. Please read the instruction to get to know whether you should run colmap.
