### ISSUE TITLE
pth can not be found and FileNotFoundError in python run.py

### ISSUE THREAD

**Issue by xiaoduoo** [mks0601/ExAvatar_RELEASE#42]
Hello, when running python run.py --root_path $ROOT/data/Custom/data/$SUBJECT_ID, I encountered the following errors:

FileNotFoundError: rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth can not be found.
FileNotFoundError: [Errno 2] No such file or directory: '../data/Custom/data/00028/keypoints_whole_body/1.json'.
However, I have already downloaded the rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth file and placed it in the mmpose/checkpoints/ folder. Additionally, the keypoints_whole_body folder is empty.

How can I resolve these issues?

**Comment by mks0601** [comment]
You need to place `rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth` at `mmpose`, not in `mmpose/checkpoints`. Let me add some lines to easily ensure this.

**Comment by xiaoduoo** [comment]
Thank you for the response. After retrying, the keypoints_whole_body/1.json file is still missing. What should I do?

**Comment by mks0601** [comment]
That is what you can get from run.py.
To be specific, mmpose will give you that.
Please run the mmpose.

**Comment by xiaoduoo** [comment]
Okay, the first error occurred with topdown_demo_with_mmdet.py:
error: unrecognized arguments: configs/wholebody_2d_keypoint/rtmpose/ubody/rtmpose-l_8xb32-270e_coco-ubody-wholebody-384x288.py dw-ll_ucoco_384.pth --input ....
This might be the reason why 1.json could not be generated. What should I do? Thank you very much!

**Comment by mks0601** [comment]
did you follow the instructions in readme? did you run copy_code.py?

**Comment by xiaoduoo** [comment]
Thank you very much for your help. The issue has been resolved.

**Comment by xiaoduoo** [comment]
Hello, I have reviewed the previous issues and solutions. The problem I am facing is that during the fitting process, the chin is normal in my smplx_optimized.mp4, but there is an issue with the chin in smplx_optimized_smoothed.mp4. What could be the possible cause of this?
