### ISSUE TITLE
How to get “diff_gaussian_rasterization_depth” module？

### ISSUE THREAD

**Issue by shanyoumu461** [mks0601/ExAvatar_RELEASE#6]
Thanks for your amazing work！As I know，`diff_gaussian_rasterization` is from original 3DGS. Where can I get `diff_gaussian_rasterization_depth` mudule?

**Comment by mks0601** [comment]
Hi, as in [here](https://github.com/mks0601/ExAvatar_RELEASE/tree/main/avatar#directory), you can visit [here](https://github.com/leo-frank/diff-gaussian-rasterization-depth).

**Comment by shanyoumu461** [comment]
Thanks for your reply^_^，I found it just now.

> Hi, as in [here](https://github.com/mks0601/ExAvatar_RELEASE/tree/main/avatar#directory), you can visit [here](https://github.com/leo-frank/diff-gaussian-rasterization-depth).
