### ISSUE TITLE
How to get snapshot 6.pth.tar

### ISSUE THREAD

**Issue by zhong2001** [mks0601/ExAvatar_RELEASE#7]
Great job! I noticed that "snapshot 6.pth.tar" was used in "run_hand4whole.py", but I couldn't find it in https://github.com/mks0601/Hand4Whole_RELEASE. That only has the download link for "snapshot 12.pth.tar", I used it instead of "snapshot 6.pth.tar", does that have an impact on the result? Because my final SMPL-X model did not fit the video characters well, it could not meet the demonstration effect of the example, and it also affected the creation and animation of my final avatar.
How do I download snapshot 6.pth.tar or how do I achieve a better SMPL-X fitting model? Thank you so much!

**Comment by mks0601** [comment]
https://github.com/mks0601/Hand4Whole_RELEASE?tab=readme-ov-file#quick-demo

**Comment by zhong2001** [comment]
Thank you for your reply. I made a stupid question, I'm going to retrain to see the fit, thanks again for your reply.
